AWSTemplateFormatVersion: 2010-09-09
Description: Notion functions
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  CertificateArnParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CertificateArnParameter

Resources:
  CloudflareOriginKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true

  CloudflareOriginKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: "alias/cloudflare-origin-key"
      TargetKeyId: !Ref CloudflareOriginKey

  CustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: notion-functions.sebsv.dev
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArnParameter

  API:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CloudflareAuthorizer:
            AuthorizerPayloadFormatVersion: "2.0"
            FunctionArn: !GetAtt CloudflareAuthorizerFunction.Arn
            EnableFunctionDefaultPermissions: true
            EnableSimpleResponses: true
        DefaultAuthorizer: CloudflareAuthorizer
      CorsConfiguration:
        AllowOrigins:
          - "*"

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref API
      DomainName: !Ref CustomDomain
      Stage: !Ref APIApiGatewayDefaultStage

  CloudflareAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authentication
      Handler: src/index.handler
      Runtime: nodejs22.x
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Ref CloudflareOriginKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        EntryPoints:
          - src/index.ts

  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world
      Handler: src/index.handler
      Runtime: nodejs22.x
      Events:
        API:
          Type: HttpApi
          Properties:
            ApiId: !Ref API
            Path: /
            Method: GET

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        EntryPoints:
          - src/index.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  Target:
    Description: CNAME registry target value
    Value: !GetAtt CustomDomain.RegionalDomainName

  APIEndpoint:
    Description: Endpoint to directly call the lambda (Only for testing)
    Value: !GetAtt API.ApiEndpoint

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

  Api:
    TracingEnabled: true
