AWSTemplateFormatVersion: 2010-09-09
Description: Notion functions
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  CertificateArnParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CertificateArnParameter

Resources:
  CustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: notion-functions.sebsv.dev
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArnParameter

  API:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          Default:
            AuthorizerPayloadFormatVersion: 2
            FunctionArn: JWTAuthorizer
      CorsConfiguration:
        AllowOrigins:
          - "*"

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref API
      DomainName: !Ref CustomDomain
      Stage: !Ref APIApiGatewayDefaultStage

  JWTAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authentication
      Handler: src/index.handler
      Runtime: nodejs22.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        EntryPoints:
          - src/index.ts

  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world
      Handler: src/index.handler
      Runtime: nodejs22.x
      Events:
        API:
          Type: HttpApi
          Properties:
            ApiId: !Ref API
            Path: /
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        EntryPoints:
          - src/index.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  WebEndpoint:
    Value: !GetAtt API.ApiEndpoint
  Target:
    Value: !GetAtt CustomDomain.RegionalDomainName

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

  Api:
    TracingEnabled: true
