AWSTemplateFormatVersion: 2010-09-09
Description: TypeScript template
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  API:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          Default:
            AuthorizerPayloadFormatVersion: 2
            FunctionArn: JWTAuthorizer
      CorsConfiguration:
        AllowOrigins:
          - "*"

  JWTAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authentication
      Handler: src/index.handler
      Runtime: nodejs22.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        EntryPoints:
          - src/index.ts

  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world
      Handler: src/index.handler
      Runtime: nodejs22.x
      Events:
        API:
          Type: HttpApi
          Properties:
            ApiId: !Ref API
            Path: /
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        EntryPoints:
          - src/index.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  WebEndpoint:
    Value: !GetAtt API.ApiEndpoint

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

  Api:
    TracingEnabled: true
